const abbreviation = {
  'BR': 'Mist',
  'CL': 'Cloudy',
  'DR': 'Drizzle',
  'FA': 'Fair (Day)',
  'FG': 'Fog',
  'FN': 'Fair (Night)',
  'FW': 'Fair & Warm',
  'HG': 'Heavy Thundery Showers with Gusty Winds',
  'HR': 'Heavy Rain',
  'HS': 'Heavy Showers',
  'HT': 'Heavy Thundery Showers',
  'HZ': 'Hazy',
  'LH': 'Slightly Hazy',
  'LR': 'Light Rain',
  'LS': 'Light Showers',
  'OC': 'Overcast',
  'PC': 'Partly Cloudy (Day)',
  'PN': 'Partly Cloudy (Night)',
  'PS': 'Passing Showers',
  'RA': 'Moderate Rain',
  'SH': 'Showers',
  'SK': 'Strong Winds, Showers',
  'SN': 'Snow',
  'SR': 'Strong Winds, Rain',
  'SS': 'Snow Showers',
  'SU': 'Sunny',
  'SW': 'Strong Winds',
  'TL': 'Thundery Showers',
  'WC': 'Windy, Cloudy',
  'WD': 'Windy',
  'WF': 'Windy, Fair',
  'WR': 'Windy, Rain',
  'WS': 'Windy, Showers'
}

const signal = [
  'HG', 'HR', 'HS', 'HT', 'LR',
  'LS', 'RA', 'SH', 'SK', 'PS',
  'SR', 'SS', 'TL', 'WS'
]

const area = [
  // 'Ang Mo Kio',
  // 'Bedok',
  // 'Bishan',
  // 'Boon Lay',
  // 'Bukit Batok',
  // 'Bukit Merah',
  // 'Bukit Panjang',
  // 'Bukit Timah',
  // 'Central Water Catchment',
  // 'Changi',
  // 'Choa Chu Kang',
  // 'Clementi',
  'City',
  // 'Geylang',
  // 'Hougang',
  // 'Jalan Bahar',
  // 'Jurong East',
  // 'Jurong Island',
  // 'Jurong West',
  // 'Kallang',
  // 'Lim Chu Kang',
  // 'Mandai',
  // 'Marine Parade',
  // 'Novena',
  // 'Pasir Ris',
  'Paya Lebar',
  // 'Pioneer',
  // 'Pulau Tekong',
  // 'Pulau Ubin',
  // 'Punggol',
  // 'Queenstown',
  // 'Seletar',
  // 'Sembawang',
  // 'Sengkang',
  // 'Sentosa',
  'Serangoon'
  // 'Southern Islands',
  // 'Sungei Kadut',
  // 'Tampines',
  // 'Tanglin',
  // 'Tengah',
  // 'Toa Payoh',
  // 'Tuas',
  // 'Western Islands',
  // 'Western Water Catchment',
  // 'Woodlands',
  // 'Yishun'
]

module.exports = { abbreviation, signal, area }
